<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x86;ARM32</Platforms>
    <StartupObject>Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\**" />
    <Compile Remove="resources\binoutput\**" />
    <EmbeddedResource Remove="Controllers\**" />
    <EmbeddedResource Remove="resources\binoutput\**" />
    <None Remove="Controllers\**" />
    <None Remove="resources\binoutput\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.0.1" />
    <PackageReference Include="Google.Protobuf" Version="3.27.2" />
    <PackageReference Include="HttpServerLite" Version="2.1.5" />
    <PackageReference Include="MongoDB.Driver" Version="3.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NLua" Version="1.7.3" />
    <PackageReference Include="Pastel" Version="5.1.0" />
    <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
    <PackageReference Include="SQLiteNetExtensions" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Campofinale.Protocol\Campofinale.Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="44_ScSyncAllMission.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="53_ScFactorySync.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="92_ScSyncAllBitset.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="93_ScSceneMapMarkSync.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Data\GachaHistory\index_noplayerfound.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Data\Static\bar.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\Static\bg.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\Static\cs_bg.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\GachaHistory\index.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Data\Static\ja-jp.otf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
	<None Update="Data\PlayerConsole\index.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
	<None Update="ScFactorySyncChapter.json">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\PlayerConsole\" />
  </ItemGroup>

</Project>
