<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x86;ARM32</Platforms>
    <StartupObject>Program</StartupObject>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\**" />
    <Compile Remove="resources\binoutput\**" />
    <EmbeddedResource Remove="Controllers\**" />
    <EmbeddedResource Remove="resources\binoutput\**" />
    <None Remove="Controllers\**" />
    <None Remove="resources\binoutput\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.27.2" />
    <PackageReference Include="HttpServerLite" Version="2.1.5" />
    <PackageReference Include="MongoDB.Driver" Version="3.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Campofinale.Protocol\Campofinale.Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="1bd049032c442d00.stardust">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="44_ScSyncAllMission.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="92_ScSyncAllBitset.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="93_ScSceneMapMarkSync.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Data\Conditions.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Data\GachaHistory\index_noplayerfound.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Data\Static\bar.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\Static\bg.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\Static\cs_bg.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\GachaHistory\index.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Data\Static\ja-jp.otf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
	<None Update="Data\PlayerConsole\index.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
	<None Update="ScFactorySyncChapter.json">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
	<None Update="Signchecker.dll">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
	<None Update="StardustUtils.dll">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\PlayerConsole\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="StardustUtils">
      <HintPath>StardustUtils.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
